<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DdnsUpdate.Core\DdnsUpdate.Core.csproj" />
    <ProjectReference Include="..\DdnsUpdate.DdnsProvider\DdnsUpdate.DdnsProvider.csproj" />
  </ItemGroup>
</Project>
